# ----------------------------------------------------------------
# English language
# ----------------------------------------------------------------
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

# banner
[en.params.banner]
enable = true
heading = "What Would You <br> Like To Read Today?"

[en.params.about_me]
# About widget
title = "Hi, I am Barry!"
image = "images/about-me.png"
bio = ""


# ----------------------------------------------------------------
# Bangla language
# ----------------------------------------------------------------
[bn]
languageName = "Bn"
languageCode = "bn-bd"
contentDir = "content/bangla"
weight = 2

# banner
[bn.params.banner]
enable = true
heading = "গল্প যেখানে বেঁচে থাকে"

# About widget
[bn.params.about_me]
title = "Hello, I am Barry!"
image = "images/about-me.png"
bio = ""
