############# french navigation ##############

# Dropdown menu
[[main]]
weight = 1
name = "homepage"
url = "/"

[[main]]
name = "About"
URL = "about-me/"
weight = 2

[[main]]
name = "Contact"
URL = "contact/"
weight = 3

# footer menu
[[footer]]
name = "Privacy Policy"
URL = "privacy-policy/"
weight = 1

[[footer]]
name = "Terms Conditions"
URL = "terms-conditions/"
weight = 2
